config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_up/:role', to: 'devise/registrations#new'
    # Sign up from CTD only for academic
    post '/ctd/sign_up', to: 'ctd#create'
    post '/ctd/sign_in', to: 'ctd_sessions#create'
  end

  devise_for :users

  resources :licenses
  resources :products
  resources :charges
  resources :ctd_downloads, only: [:index, :create]

  root to: 'pages#index'

  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/license_template', to: 'pages#license_template', as: :license_template

end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  before_action :set_license, only: [:show, :edit, :update, :destroy]

  # GET /licenses
  # GET /licenses.json
  def index
    @licenses = License.all
  end

  # GET /licenses/1
  # GET /licenses/1.json
  def show
    respond_to do |format|
      format.html
       # display a pdf that already exists
      format.pdf do
        render pdf: "license_agreement",
              template: "licenses/license.pdf.erb",
              locals: {:license => @license}
      end
    end
  end

  # GET /licenses/new
  def new
    @product = Product.find(params[:product_id])
    @license = @product.licenses.build(price: params[:price])
  end

  # GET /licenses/1/edit
  def edit
  end

  # POST /licenses
  # POST /licenses.json
  def create
    @license = License.new(license_params)

    respond_to do |format|
      if @license.save
        format.html { redirect_to :controller => 'charges', :action => 'new', :license_id => @license.id}

        format.json { render :show, status: :created, location: @license }
        save_pdf
      else
        format.html { render :new }
        format.json { render json: @license.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /licenses/1
  # PATCH/PUT /licenses/1.json
  def update
    respond_to do |format|
      if @license.update(license_params)
        format.html { redirect_to @license, notice: 'License was successfully updated.' }
        format.json { render :show, status: :ok, location: @license }
      else
        format.html { render :edit }
        format.json { render json: @license.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /licenses/1
  # DELETE /licenses/1.json
  def destroy
    @license.destroy
    respond_to do |format|
      format.html { redirect_to licenses_url, notice: 'License was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_license
      @license = License.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def license_params
      params.require(:license).permit(:user_id, :product_id, :price, :expiration_date, :address, :accept)
    end

    def save_pdf
      body_html = render_to_string( template: "licenses/template/_save_license.pdf.erb" )
      pdf = WickedPdf.new.pdf_from_string(
          body_html,
          orientation: 'Portrait',
          margin: { bottom: 20, top: 30 })

       # then save to a file
      save_path = Rails.root.join('pdfs',"license_#{Time.now}.pdf")
      File.open(save_path, 'wb') do |file|
        file << pdf
    end
   end
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/views/licenses/_form.html.erb
<%= form_for(license) do |f| %>
  <% if license.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(license.errors.count, "error") %> prohibited this license from being saved:</h2>

      <ul>
      <% license.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :expiration_date %>
    <%= f.date_select :expiration_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/licenses/edit.html.erb
<h1>Editing License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Show', @license %> |
<%= link_to 'Back', licenses_path %>

app/views/licenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Licenses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Price</th>
      <th>Expiration date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @licenses.each do |license| %>
      <tr>
        <td><%= license.user %></td>
        <td><%= license.product %></td>
        <td><%= license.price %></td>
        <td><%= license.expiration_date %></td>
        <td><%= link_to 'Show', license %></td>
        <td><%= link_to 'Edit', edit_license_path(license) %></td>
        <td><%= link_to 'Destroy', license, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New License', new_license_path %>

app/views/licenses/license.pdf.erb
<section id="license">
    <h1 class="center">License Agreement</h1>
    <%= form_for(@license) do |f| %>
    <div class='license-agreement container z-depth-2'>
      <h6 class="">
        <%= Product.find(@license.id).title %>
        License Agreement
      </h6>

        <p>THIS AGREEMENT CONCERNS YOUR RIGHTS AND OBLIGATIONS READ IT CAREFULLY</p>
        <p>This End-User Agreement ("EULA") is a legal agreement between
            <%= User.find(@license.user_id).organization %>
            ("Licensee"), having its principal office at
            <%= license.address%>, and North Carolina State University, a constituent institution of the University of North Carolina and a nonprofit educational and research institution
                organized under the laws of North Carolina ("NCSU"), having its principal office at Campus Box 8210, Raleigh, North Carolina 27695-8210, for the software identified as
            <%= Product.find(@license.id).title %>, as described in NCSU File No.
            <%= Product.find(@license.id).ncsu_file_no %>
            (all together, the "Software").
        </p>
        <p>
            CodeAlliance is a third party distributor of software, and through its online marketplace, makes this Software available for license to Licensee under this EULA. CodeAlliance may also make the Software accessible and available for distribution.
        </p>
        <p>
            BY CLICKING "ACCEPT" ON THE "REVIEW AND ACCEPT AGREEMENT" PAGE DURING THE LICENSING PROCESS, BY SIGNING BELOW OR BY DOWNLOADING, INSTALLING, COPYING, OR OTHERWISE USING THE SOFTWARE, YOU, THE LICENSEE, AGREE TO BE BOUND BY THE TERMS OF THIS EULA. IF
            YOU DO NOT AGREE TO THE TERMS OF THIS EULA, YOU ARE NOT AUTHORIZED TO USE THE SOFTWARE.
        </p>
        <p>
            LICENSE FEE: License Fee is <%= number_to_currency(@license.price) %>
        </p>
        <p>
            1. OWNERSHIP AND LICENSE. The Software was created by NCSU, and NCSU is willing to license the Software to end-users, such as Licensee. Licensee has no rights to the Software other than as expressly stated in this EULA and as may be available under
            applicable law. The Software is protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties.
        </p>
        <p>
            2. GRANT OF LICENSE. This EULA grants to Licensee the following rights:
        </p>
        <p>
            a) A worldwide, non-transferable, non-sublicensable, non-exclusive license to use the Software for internal purposes only.
        </p>
        <p>
            b) Installation and Use. Licensee may install and use a copy of the Software on a single laptop, personal computer, workstation or mobile device. The Software may be installed so that it is accessible to multiple users over a network so long as the network is internal to Licensee.
        </p>
        <p>

            c) Backup Copies. Licensee may make a backup copy of the Software for the computer on which the Software is installed.
        </p>
        <p>

            3. OTHER RIGHTS AND LIMITATIONS. Limitations on Copyright. Licensee may not reproduce, publicly display or make derivative works of the Software. Notices and Markings. Licensee must maintain all copyright notices and other proprietary markings on all
            copies of the Software. Separation of Components. The Software is licensed as a single product. Its component parts may be separated for use so long as the appropriate copyright notice is clearly marked for the end-users.
        </p>
        <p>
            Distribution or Transfer. Licensee may not transfer, by sublicense or otherwise, any of its rights under this EULA. Licensee may not distribute copies of the Software to third parties.
        </p>
        <p>
            Rental. Licensee may not rent, lease, or lend the Software.
        </p>
        <p>
            Term. This EULA will be valid for one year.
        </p>
        <p>Termination. Without prejudice to any other rights or terms outlined, NCSU may terminate this EULA if Licensee fails to comply with the terms and conditions of this EULA. In such event, Licensee must destroy all copies of the Software and all of
            its component parts.
        </p>
        <p>
            4. COPYRIGHT. All title and copyrights in and to the Software and any copies of all or parts of the Software are owned by NCSU.
        </p>
        <p>
            5. LICENSE FEE. Licensee shall pay, upon checkout, the License Fee and any applicable taxes, duties, fees, excises or other charges. All amounts payable hereunder by Licenseenon-refundable and non-creditable. All amounts payable hereunder by Licensee
            shall be payable in United States funds.
        </p>
        <p>
            6. ACCESS TO MATERIALS. Within one (1) week of payment of the License Fee, following execution of this EULA, the Software and any accompanying Software documentation, includin<br>g any installation instructions will be made accessible to Licensee.
        </p>
        <p>
            7. EXPORT RESTRICTIONS. Licensee agrees that it will not export or re-export the Software to any country,

        </p>
        <p>
            8. NO WARRANTIES. NCSU and CodeAlliance expressly disclaim any warranty for the Software. THE SOFTWARE AND ANY RELATED DOCUMENTATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE
            IMPLIED WARRANTIES OR MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. The entire risk arising out of the use or performance of the Software remains with Licensee.
        </p>
        <p>
            9. LIMITATIONS ON DAMAGES. NCSU and CodeAlliance shall not be liable for any damages (including, without limitation, damages for loss of life or other pecuniary loss) arising out of the use or inability to use this Software. IN NO EVENT SHALL THE
            TOTAL LIABILITY OF NCSU and CodeAlliance, THERE REPRESENTATIVES, AGENTS, OR SUPPLIERS UNDER THIS EULA OR OTHERWISE IN CONNECTION WITH THE SOFTWARE, FOR ANY REASON, EXCEED THE AMOUNT OF THE LICENSE FEE PAID BY THE LICENSEE TO FOR USE OF THE SOFTWARE.
        </p>
        <p>
            10. NOTICE. For the purpose of all written communications and notices between the parties, the address for NCSU is: Office of Technology Commercialization and New Ventures, NORTH CAROLINA STATE UNIVERSITY, Attn: Assistant Vice Chancellor for
            Technology Commercialization and New Ventures, Campus Box 8210, Raleigh, NC 27695-8210 USA and the address for Licensee is as listed above, or any other addresses of which either party shall notify the other party in writing.
        </p>
        <p>
            11. MISCELLANEOUS. NCSU is based in and directs its operations from locations in the State of North Carolina, United States of America. This EULA is governed by the laws of the State of North Carolina, without reference to conflict of laws
            provisions. All legal proceedings relating to the Software or the formation or interpretation of this EULA shall be brought only in the state or federal courts located in Raleigh, North Carolina, and Licensee hereby expressly submit to the
            jurisdiction of such courts and consent to extra-territorial service of process.
        </p>
        <p>
            12. ELECTRONIC COPY. The parties to this document agree that a copy of the original signature (including an electronic copy) may be used for any and all purposes for which the original signature may have been used. The parties further waive any right
            to challenge the admissibility or authenticity of this document in a court of law based solely on the absence of an original signature.
        </p>


        <p>Accepted by: <%= User.find(@license.user_id).name %></p>
        <p>Date: <%= @license.created_at %></p>
    </div>
    <% end %>

</section>

app/views/licenses/new.html.erb
<section id="license">
    <h1 class="center">License Agreement</h1>
    <%= form_for(@license) do |f| %>
    <div class='license-agreement container z-depth-2'>
      <h6 class="">
        <%= @product.title %>
        License Agreement
      </h6>

        <p>THIS AGREEMENT CONCERNS YOUR RIGHTS AND OBLIGATIONS READ IT CAREFULLY</p>
        <p>This End-User Agreement (“EULA”) is a legal agreement between
            <%= current_user.organization %>
            (“Licensee”), having its principal office at
            <%= f.text_field(:address, class: 'license-user_input', placeholder: 'type company address') %>, and North Carolina State University, a constituent institution of the University of North Carolina and a nonprofit educational and research institution
                organized under the laws of North Carolina (“NCSU”), having its principal office at Campus Box 8210, Raleigh, North Carolina 27695-8210, for the software identified as
            <%= @product.title %>, as described in NCSU File No.
            <%= @product.ncsu_file_no %>
            (all together, the “Software”).
        </p>
        <p>
            CodeAlliance is a third party distributor of software, and through its online marketplace, makes this Software available for license to Licensee under this EULA. CodeAlliance may also make the Software accessible and available for distribution.
        </p>
        <p>
            BY CLICKING “ACCEPT” ON THE “REVIEW AND ACCEPT AGREEMENT” PAGE DURING THE LICENSING PROCESS, BY SIGNING BELOW OR BY DOWNLOADING, INSTALLING, COPYING, OR OTHERWISE USING THE SOFTWARE, YOU, THE LICENSEE, AGREE TO BE BOUND BY THE TERMS OF THIS EULA. IF
            YOU DO NOT AGREE TO THE TERMS OF THIS EULA, YOU ARE NOT AUTHORIZED TO USE THE SOFTWARE.
        </p>
        <p>
            LICENSE FEE: License Fee is <%= number_to_currency(@license.price) %>
        </p>
        <p>
            1. OWNERSHIP AND LICENSE. The Software was created by NCSU, and NCSU is willing to license the Software to end-users, such as Licensee. Licensee has no rights to the Software other than as expressly stated in this EULA and as may be available under
            applicable law. The Software is protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties.
        </p>
        <p>
            2. GRANT OF LICENSE. This EULA grants to Licensee the following rights:
        </p>
        <p>
            a) A worldwide, non-transferable, non-sublicensable, non-exclusive license to use the Software for internal purposes only.
        </p>
        <p>
            b) Installation and Use. Licensee may install and use a copy of the Software on a single laptop, personal computer, workstation or mobile device. The Software may be installed so that it is accessible to multiple users over a network so long as the network is internal to Licensee.
        </p>
        <p>

            c) Backup Copies. Licensee may make a backup copy of the Software for the computer on which the Software is installed.
        </p>
        <p>

            3. OTHER RIGHTS AND LIMITATIONS. Limitations on Copyright. Licensee may not reproduce, publicly display or make derivative works of the Software. Notices and Markings. Licensee must maintain all copyright notices and other proprietary markings on all
            copies of the Software. Separation of Components. The Software is licensed as a single product. Its component parts may be separated for use so long as the appropriate copyright notice is clearly marked for the end-users.
        </p>
        <p>
            Distribution or Transfer. Licensee may not transfer, by sublicense or otherwise, any of its rights under this EULA. Licensee may not distribute copies of the Software to third parties.
        </p>
        <p>
            Rental. Licensee may not rent, lease, or lend the Software.
        </p>
        <p>
            Term. This EULA will be valid for one year.
        </p>
        <p>Termination. Without prejudice to any other rights or terms outlined, NCSU may terminate this EULA if Licensee fails to comply with the terms and conditions of this EULA. In such event, Licensee must destroy all copies of the Software and all of
            its component parts.
        </p>
        <p>
            4. COPYRIGHT. All title and copyrights in and to the Software and any copies of all or parts of the Software are owned by NCSU.
        </p>
        <p>
            5. LICENSE FEE. Licensee shall pay, upon checkout, the License Fee and any applicable taxes, duties, fees, excises or other charges. All amounts payable hereunder by Licenseenon-refundable and non-creditable. All amounts payable hereunder by Licensee
            shall be payable in United States funds.
        </p>
        <p>
            6. ACCESS TO MATERIALS. Within one (1) week of payment of the License Fee, following execution of this EULA, the Software and any accompanying Software documentation, includin<br>g any installation instructions will be made accessible to Licensee.
        </p>
        <p>
            7. EXPORT RESTRICTIONS. Licensee agrees that it will not export or re-export the Software to any country,

        </p>
        <p>
            8. NO WARRANTIES. NCSU and CodeAlliance expressly disclaim any warranty for the Software. THE SOFTWARE AND ANY RELATED DOCUMENTATION IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE
            IMPLIED WARRANTIES OR MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. The entire risk arising out of the use or performance of the Software remains with Licensee.
        </p>
        <p>
            9. LIMITATIONS ON DAMAGES. NCSU and CodeAlliance shall not be liable for any damages (including, without limitation, damages for loss of life or other pecuniary loss) arising out of the use or inability to use this Software. IN NO EVENT SHALL THE
            TOTAL LIABILITY OF NCSU and CodeAlliance, THERE REPRESENTATIVES, AGENTS, OR SUPPLIERS UNDER THIS EULA OR OTHERWISE IN CONNECTION WITH THE SOFTWARE, FOR ANY REASON, EXCEED THE AMOUNT OF THE LICENSE FEE PAID BY THE LICENSEE TO FOR USE OF THE SOFTWARE.
        </p>
        <p>
            10. NOTICE. For the purpose of all written communications and notices between the parties, the address for NCSU is: Office of Technology Commercialization and New Ventures, NORTH CAROLINA STATE UNIVERSITY, Attn: Assistant Vice Chancellor for
            Technology Commercialization and New Ventures, Campus Box 8210, Raleigh, NC 27695-8210 USA and the address for Licensee is as listed above, or any other addresses of which either party shall notify the other party in writing.
        </p>
        <p>
            11. MISCELLANEOUS. NCSU is based in and directs its operations from locations in the State of North Carolina, United States of America. This EULA is governed by the laws of the State of North Carolina, without reference to conflict of laws
            provisions. All legal proceedings relating to the Software or the formation or interpretation of this EULA shall be brought only in the state or federal courts located in Raleigh, North Carolina, and Licensee hereby expressly submit to the
            jurisdiction of such courts and consent to extra-territorial service of process.
        </p>
        <p>
            12. ELECTRONIC COPY. The parties to this document agree that a copy of the original signature (including an electronic copy) may be used for any and all purposes for which the original signature may have been used. The parties further waive any right
            to challenge the admissibility or authenticity of this document in a court of law based solely on the absence of an original signature.
        </p>
        <p>
            <%= f.check_box(:accept, { class: "input-field" }, true, false)%>
            <label for='license_accept'>I agree to the terms and conditions of this license agreement.</label>
        </p>
        <%= f.hidden_field(:product_id)%>
        <%= f.hidden_field(:price)%>
        <%= f.hidden_field(:user_id, :value => current_user.id)%>
        <%= f.submit 'Submit license', class: "btn submit-license disabled waves-effect waves-light white-text" %>
    </div>
    <% end %>

</section>