config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_up/:role', to: 'devise/registrations#new'
    # Sign up from CTD only for academic
    post '/ctd/sign_up', to: 'ctd#create'
    post '/ctd/sign_in', to: 'ctd_sessions#create'
  end

  devise_for :users

  resources :licenses
  resources :products
  resources :charges
  resources :ctd_downloads, only: [:index, :create]

  root to: 'pages#index'

  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/license_template', to: 'pages#license_template', as: :license_template

end

app/views/pages/index.html.erb
<section id="splash" class="z-depth-1 valign-wrapper">
  <div class="container">
    <%= image_tag("tech.svg", class: 'tech-image hide-on-med-and-down') %>
    <div class="splash-message white-text center-align">
        <h1>Software & Data at your fingertips.</h1>
        <h5>Our goal is to provide greater access to data and software produced in leading research institutions across country.</h5>
        <%= link_to 'Get Started', new_user_registration_path, class: 'btn waves-effect' %>
    </div>
  </div>
</section>

<section id="about">
  <div class="container">
    <div class="about-title">
      <h4 class="center-align with-subtitle">Catalyst Research Alliance</h4>
      <h5 class="subtitle center-align">A marketplace for innovative intellectual property and research data</h5>
    </div>
    <div class="row three-paragraphs center-align">
      <div class="col m4 s12">
        <div class="row">
          <div class="col s4 offset-s4 m6 offset-m3">
            <%= image_tag("search.svg") %>
          </div>
        </div>
        <h5>Software</h5>
        <p>Catalyst is a marketplace to find software produced by leading researchers across a variety of fields at universities.</p>
      </div>
      <div class="col m4 s12">
        <div class="row">
          <div class="col s4 offset-s4 m6 offset-m3">
            <%= image_tag("cloud-computing.svg") %>
          </div>
        </div>
        <h5>Data</h5>
        <p>Our datasets created and curated by researchers in the fields of agriculture, genomics, therapeutics, and environmental sciences.</p>
      </div>
      <div class="col m4 s12">
        <div class="row">
          <div class="col s4 offset-s4 m6 offset-m3">
            <%= image_tag("idea.svg", class: 'svg-shadow') %>
          </div>
        </div>
        <h5>Partner</h5>
        <p>North Carolina State University is our first partner. Contact us to find out more about becoming a partner with Catalyst Research.</p>
      </div>
    </div>
  </div>
</section>

app/views/pages/license_template.html.erb
<h1>CTD License</h1>

<p>
  Form of User Agreement
<br>
THIS AGREEMENT CONCERNS YOUR RIGHTS AND OBLIGATIONS READ IT CAREFULLY
<br>
This End-User Agreement (“EULA”) is a legal agreement between ________________. (“Licensee”), having its principal office at _______________________, and North Carolina State University, a constituent institution of the University of North Carolina and a nonprofit educational and research institution organized under the laws of North Carolina (“NCSU”), having its principal office at Campus Box 8210, Raleigh, North Carolina 27695-8210, for the software identified as __________________ , as described in NCSU File No. ________ (all together, the “Software”).
<br>
CodeAlliance is a third party distributor of software, and through its online marketplace, makes this Software available for license to Licensee under this EULA. CodeAlliance may also make the Software accessible and available for distribution.
<br>
BY CLICKING “ACCEPT” ON THE “REVIEW AND ACCEPT AGREEMENT” PAGE DURING THE LICENSING PROCESS, BY SIGNING BELOW OR BY DOWNLOADING, INSTALLING, COPYING, OR OTHERWISE USING THE SOFTWARE, YOU, THE LICENSEE, AGREE TO BE BOUND BY THE TERMS OF THIS EULA. IF YOU DO NOT AGREE TO THE TERMS OF THIS EULA, YOU ARE NOT AUTHORIZED TO USE THE SOFTWARE.
<br>
LICENSE FEE:
License Fee is $____________.

<br>
1. OWNERSHIP AND LICENSE. The Software was created by NCSU, and NCSU is willing to license the Software to end-users, such as Licensee.  Licensee has no rights to the Software other than as expressly stated in this EULA and as may be available under applicable law.  The Software is protected by copyright laws and international copyright treaties, as well as other intellectual property laws and treaties.
<br/>
2. GRANT OF LICENSE. This EULA grants to Licensee the following rights:
<br>
a)     A worldwide, non-transferable, non-sublicensable, non-exclusive license to use the Software for internal purposes only.
<br>
b)     Installation and Use. Licensee may install and use a copy of the Software on a single laptop, personal computer, workstation or mobile device. The Software may be installed so that it is accessible to multiple users over a network so long as the network is internal to Licensee.
<br>

c)     Backup Copies. Licensee may make a backup copy of the Software for the computer on which the Software is installed.
<br>

3. OTHER RIGHTS AND LIMITATIONS.
Limitations on Copyright. Licensee may not reproduce, publicly display or make derivative works of the Software.
Notices and Markings. Licensee must maintain all copyright notices and other proprietary markings on all copies of the Software.
Separation of Components. The Software is licensed as a single product. Its component parts may be separated for use so long as the appropriate copyright notice is clearly marked for the end-users.
<br>
Distribution or Transfer. Licensee may not transfer, by sublicense or otherwise, any of its rights under this EULA.  Licensee may not distribute copies of the Software to third parties.
<br>
Rental. Licensee may not rent, lease, or lend the Software.
<br>
Term. This EULA will be valid for one year.
<br>Termination. Without prejudice to any other rights or terms outlined, NCSU may terminate this EULA if Licensee fails to comply with the terms and conditions of this EULA. In such event, Licensee must destroy all copies of the Software and all of its component parts.

<br>
4. COPYRIGHT. All title and copyrights in and to the Software and any copies of all or parts of the Software are owned by NCSU.
<br>
5. LICENSE FEE. Licensee shall pay, upon checkout, the License Fee and any applicable taxes, duties, fees, excises or other charges. All amounts payable hereunder by Licenseenon-refundable and non-creditable. All amounts payable hereunder by Licensee shall be payable in United States funds.
<br>
6. ACCESS TO MATERIALS. Within one (1) week of payment of the License Fee, following execution of this EULA, the Software and any accompanying Software documentation, includin<br>g any installation instructions will be made accessible to Licensee.
<br>
7. EXPORT RESTRICTIONS.  Licensee agrees that it will not export or re-export the Software to any country,

<br>
8. NO WARRANTIES. NCSU and CodeAlliance expressly disclaim any warranty for the Software. THE SOFTWARE AND ANY RELATED DOCUMENTATION IS PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE IMPLIED WARRANTIES OR MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NONINFRINGEMENT. The entire risk arising out of the use or performance of the Software remains with Licensee.
<br>
9. LIMITATIONS ON DAMAGES.  NCSU and CodeAlliance shall not be liable for any damages (including, without limitation, damages for loss of life or other pecuniary loss) arising out of the use or inability to use this Software.  IN NO EVENT SHALL THE TOTAL LIABILITY OF NCSU and CodeAlliance, THERE REPRESENTATIVES, AGENTS, OR SUPPLIERS UNDER THIS EULA OR OTHERWISE IN CONNECTION WITH THE SOFTWARE, FOR ANY REASON, EXCEED THE AMOUNT OF THE LICENSE FEE PAID BY THE LICENSEE TO FOR USE OF THE SOFTWARE.
<br>
10. NOTICE. For the purpose of all written communications and notices between the parties, the address for NCSU is: Office of Technology Commercialization and New Ventures, NORTH CAROLINA STATE UNIVERSITY, Attn: Assistant Vice Chancellor for Technology Commercialization and New Ventures, Campus Box 8210, Raleigh, NC 27695-8210 USA and the address for Licensee is as listed above, or any other addresses of which either party shall notify the other party in writing.
<br>
11. MISCELLANEOUS.  NCSU is based in and directs its opera<br>tions from locations in the State of North Carolina, United States of America. This EULA is governed by the laws of the State of North Carolina, without reference to conflict of laws provisions. All legal proceedings relating to the Software or the formation or interpretation of this EULA shall be brought only in the state or federal courts located in Raleigh, North Carolina, and Licensee hereby expressly submit to the jurisdiction of such courts and consent to extra-territorial service of process.
<br>
12. ELECTRONIC COPY. The parties to this document agree that a copy of the original signature (including an electronic copy) may be used for any and all purposes for which the original signature may have been used.  The parties further waive any right to challenge the admissibility or authenticity of this document in a court of law based solely on the absence of an original signature.

<br>

</p>

<%# TODO: NEED HTML form tag to allow users to "Agree to license terms.""
 %>

<%# TODO: Send params re contract to create action on license controller with params and pdf of contract. %>

<%# TODO: User should be redirected to payments page. %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="A month's subscription"
        data-amount="500"
        data-locale="auto"></script>

<!-- <%= link_to 'Credit Card Payment', new_charge_path %> -->
<%= link_to 'Back', licenses_path %>

app/views/pages/pricing.html.erb
<section id="pricing-page">
  <div class="parallax-container">
    <div class="parallax">
      <%= image_tag("abstract-vectors.png") %>
    </div>
    <div class="container">
      <div class="row white-text center-align">
        <h2>Choose your plan.</h2>
        <h5>Hunt by meowing loudly at 5am next to human slave food dispenser cat is love, cat is life for chase laser for kitty poochy meowzer!</h5>
      </div>
    </div>
  </div>
  <div class="pricing-wrapper">
    <div class="row">
      <div class="col s12 m6 l4 tier-1">
        <div class="card white hoverable">
          <h4 class="center medium-blue white-text">Tier 1</h4>
          <div class="card-image">
            <%= image_tag("system.svg") %>
          </div>
          <div class="card-content grey-text center">
            <h5 class="grey-text text-darken-1">Features</h5>
            <p class="valign-wrapper"><i class="material-icons">done</i>100 Employees</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
            <h3 class="medium-blue-text">$3,000</h3>
          </div>
          <div class="center card-action">
            <%= link_to 'Buy Now', license_template_path, class: "btn waves-effect waves-light white-text medium-blue" %>
          </div>
        </div>
      </div>
      <div class="col s12 m6 l4 tier-2">
        <div class="card white hoverable">
          <h4 class="center gold white-text">Tier 2</h4>
          <div class="card-image">
            <%= image_tag("astronaut.svg") %>
          </div>
          <div class="card-content grey-text center">
            <h5 class="grey-text text-darken-1">Features</h5>
            <p class="valign-wrapper"><i class="material-icons">done</i> < 250 Employees</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
            <h3 class="gold-text text-darken-3">$5,000</h3>
          </div>
          <div class="center card-action">
            <%= link_to 'Buy Now', license_template_path, class: "btn waves-effect waves-light white-text gold" %>
          </div>
        </div>
      </div>
      <div class="col s12 m6 l4 tier-3">
        <div class="card white hoverable">
          <h4 class="center rusted-red white-text">Tier 3</h4>
          <div class="card-image">
            <%= image_tag("rocket.svg") %>
          </div>
          <div class="card-content grey-text center">
            <h5 class="grey-text text-darken-1">Features</h5>
            <p class="valign-wrapper"><i class="material-icons">done</i> > 250 Employees</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
            <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
            <h3 class="rusted-red-text text-darken-3">$10,000</h3>
          </div>
          <div class="center card-action">
            <%= link_to 'Buy Now', license_template_path, class: "btn waves-effect waves-light white-text rusted-red" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <article class="faq">
    <div class="container">
      <h2 class="center">Frequently asked questions</h2>

      <ul class="collapsible" data-collapsible="expandable">
        <li>
          <div class="collapsible-header">
            <p>How does the pricing work?<i class="material-icons right">arrow_drop_down</i></p>
          </div>
          <div class="collapsible-body">
            <span>Lorem kitty kitty kat ipsum dolor sit amet.</span>
          </div>
        </li>

        <li>
          <div class="collapsible-header">
            <p>I have more questions!<i class="material-icons right">arrow_drop_down</i></p>
          </div>
          <div class="collapsible-body">
            <span>Just send us an email at <a href="#">example@mail.com</a>, we'll be more than happy to help.</span>
          </div>
        </li>

        <li>
          <div class="collapsible-header">
            <p>I have more questions!<i class="material-icons right">arrow_drop_down</i></p>
          </div>
          <div class="collapsible-body">
            <span>Just send us an email at <a href="#">example@mail.com</a>, we'll be more than happy to help.</span>
          </div>
        </li>

        <li>
          <div class="collapsible-header">
            <p>I have more questions!<i class="material-icons right">arrow_drop_down</i></p>
          </div>
          <div class="collapsible-body">
            <span>Just send us an email at <a href="#">example@mail.com</a>, we'll be more than happy to help.</span>
          </div>
        </li>

        <li>
          <div class="collapsible-header">
            <p>I have more questions!<i class="material-icons right">arrow_drop_down</i></p>
          </div>
          <div class="collapsible-body">
            <span>Just send us an email at <a href="#">example@mail.com</a>, we'll be more than happy to help.</span>
          </div>
        </li>
      </ul>

    </div>
  </article>
</section>