config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_up/:role', to: 'devise/registrations#new'
    # Sign up from CTD only for academic
    post '/ctd/sign_up', to: 'ctd#create'
    post '/ctd/sign_in', to: 'ctd_sessions#create'
  end

  devise_for :users

  resources :licenses
  resources :products
  resources :charges
  resources :ctd_downloads, only: [:index, :create]

  root to: 'pages#index'

  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/license_template', to: 'pages#license_template', as: :license_template

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :licenses
  has_many :CTD_downloads

  has_attached_file :image, styles: { medium: "250x250" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search_input)
    if !search_input.nil? && search_input.length > 1
      search_results = []
      search_terms = search_input.strip.split(" ")
      search_terms.each do |search|
        search_results << where("title ILIKE ? OR summary ILIKE ? OR detailed_description ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
      end
        results = search_results.flatten
        results.uniq
    else
      Product.all
    end
  end

  # has_attached_file :image,
  #                  styles: { medium: "640x" },
  #                  storage: :s3,
  #                  s3_credentials: Product.new{ |a| a.instance.s3_credentials },
  #                  s3_region: 'us-east-1'
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

 #  def s3_credentials
 #   {
 #     bucket: ENV['S3_PRODUCTS_BUCKET'],
 #     access_key_id: ENV['S3_ACCESS_KEY_ID'],
 #     secret_access_key: ENV['S3_SECRET_ACCESS_KEY']
 #   }
 # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  before_action :deny_access, :unless => :is_admin?, except: [:show, :index]

  # GET /products
  # GET /products.json
  def index
    @products = Product.search(params[:search])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :developer, :email, :institution, :category, :price, :summary, :detailed_description, :image, :bucket)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :developer %>
    <%= f.text_field :developer %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :institution %>
    <%= f.text_field :institution %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :product_summary %>
    <%= f.text_field :summary %>
  </div>

  <div class="field">
    <%= f.label :detailed_description %>
    <%= f.text_field :detailed_description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
   <%= f.label :image %>
   <%= f.file_field :image, class: 'field' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="products-wrapper">

  <section class="search-wrapper">
    <h5 class="center">Search Products</h5>
    <form class="white">
      <div class="input-field valign-wrapper">
        <input id="search" type="search" placeholder="Enter search term" required>
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons">close</i>
      </div>
    </form>
  </section>

  <section id="products">
    <div class='search-header'>
      <% if params[:search].nil? %>
        <%='Featured Technologies' %>
      <% else %>
        <%='Search Results' %>
      <% end %>
    </div>
    <ul>
      <% @products.each do |product| %>
      <li>
        <div class="product">
          <div class="details">
            <h3><%= product.title %></h3>
            <p><%= product.summary %></p>
          </div>
          <div class="developer hide-on-med-and-down">
            <h5><%= product.institution %></h5>
            <h6><%= product.developer %></h6>
          </div>
          <%= link_to 'Details', product, class: "btn-flat waves-effect waves-light col s12" %>
        </div>
      </li>

    </ul>

      <% if is_admin? %>
      <%= link_to 'Show', product_path(product) %>
      <%= link_to 'Edit', edit_product_path(product) %>
      <%= link_to 'Destroy', product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'New Product', new_product_path %>
      <% end %>
    <% end %>
  </section>

</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<section id="details-page">
  <p id="notice"><%= notice %></p>
  <h5 class="center">Product Details</h5>
  <div class="container">
    <div class="summary-wrapper row">
      <div class="title col s12">
        <h3><%= @product.title %></h3>
      </div>
      <div class="details-wrapper row">
        <div class="summary col m8 s12">
          <p><%= @product.summary %></p>
          <p><strong>Developer:</strong> <%= @product.developer %></p>
        </div>
        <div class="details col m4 s12">
          <img src="<%= @product.image.url(:medium) %>" alt="<%= @product.title %>" />
        </div>
      </div>
    </div>

    <div class="description row">
      <h4>Product Description</h4>
      <div class="detailed-description col s12 m8">
        <p><%= @product.detailed_description %></p>
      </div>
      <div class="images col s12 m4">
        <p><strong>Category:</strong> <%= @product.category %></p>
        <p><strong>University:</strong> <%= @product.institution %></p>
        <p><strong>Email:</strong> <%= @product.email %></p>
      </div>
    </div>
  </div>


  <div class="pricing-wrapper">
    <h2>Purchase a License</h2>
    <div class="pricing container">
      <% if @product.id == 1 %>
      <div class="row">
        <div class="tier-1">
          <div class="price-card white hoverable">
            <h4>100 Employees</h4>
            <h3>$3,000</h3>
            <div class="card-content grey-text center">
              <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
              <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
              <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
            </div>
            <div class="center card-action">
              <%= link_to 'Purchase License', { :controller => 'licenses', :action => 'new', :product_id => @product, :price => '3000' }, class: "btn-flat waves-effect waves-light" %>
            </div>
          </div>
        </div>
        <div class="tier-2">
          <div class="price-card white hoverable">
            <h4> < 250 Employee</h4>
            <h3>$5,000</h3>
            <div class="card-content grey-text center">
              <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
              <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
              <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
            </div>
            <div class="center card-action">
              <%= link_to 'Purchase License', { :controller => 'licenses', :action => 'new', :product_id => @product, :price => '5000.55' }, class: "btn-flat waves-effect waves-light" %>
            </div>
          </div>
        </div>

        <div class="tier-3">
          <div class="price-card white hoverable">
            <h4> > 250 Employees</h4>
            <h3>$10,000</h3>
            <div class="card-content grey-text center">
              <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
              <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
              <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
            </div>
            <div class="center card-action">
              <%= link_to 'Purchase License', { :controller => 'licenses', :action => 'new', :product_id => @product, :price => '10000' }, class: "btn-flat waves-effect waves-light" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% else %>
  <div class="tier-4">
    <div class="price-card white hoverable">
      <h4> Download</h4>
      <h3>$10,000</h3>
      <div class="card-content grey-text center">
        <p class="valign-wrapper"><i class="material-icons">done</i>Annual site license</p>
        <p class="valign-wrapper"><i class="material-icons">done</i>Unlimited downloads</p>
        <p class="valign-wrapper"><i class="material-icons">done</i>Internal use only</p>
      </div>
      <div class="center card-action">
        <%= link_to 'Purchase License', { :controller => 'licenses', :action => 'new', :product_id => @product, :price => '10000' }, class: "btn-flat waves-effect waves-light" %>
      </div>
    </div>
  </div>
  <% end %>
</section>