config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_up/:role', to: 'devise/registrations#new'
    # Sign up from CTD only for academic
    post '/ctd/sign_up', to: 'ctd#create'
    post '/ctd/sign_in', to: 'ctd_sessions#create'
  end

  devise_for :users

  resources :licenses
  resources :products
  resources :charges
  resources :ctd_downloads, only: [:index, :create]

  root to: 'pages#index'

  get '/pricing', to: 'pages#pricing', as: :pricing
  get '/license_template', to: 'pages#license_template', as: :license_template

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @license = License.find(params[:license_id])
  end

  def create
    # Amount in cents
    @amount = 15000

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

###############

# def create
#   @order = Order.new(order_params)
#   charge_error = nil
#
#   if @order.valid?
#     begin
#       customer = Stripe::Customer.create(
#         :email => 'example@stripe.com',
#         :card  => params[:stripeToken])
#
#       charge = Stripe::Charge.create(
#         :customer    => customer.id,
#         :amount      => 5000,
#         :description => 'Rails Stripe customer',
#         :currency    => 'usd')
#
#     rescue Stripe::CardError => e
#       charge_error = e.message
#     end
#     if charge_error
#       flash[:error] = charge_error
#       render :new
#     else
#       @order.save
#       redirect_to (successful page)
#     end
#   else
#     flash[:error] = 'one or more errors in your order'
#     render :new
#   end
# end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$10,000</strong>!</h2>

app/views/charges/new.html.erb
<section id="payment">
  <%= link_to "View License PDF", license_path(@license, format: :pdf), :target => "_blank", class: "btn-flat pdf waves-effect waves-light" %>

  <div class="invoice z-depth-3">
    <div class="invoice-head">
      <div class="order-user">
        <h4><%= current_user.organization %></h4>
        <span><h6>Address: </h6><p><%= @license.address %></p><span>
      </div>
      <div class="order-details">
        <h5>Order</h5>
      </div>
    </div>
    <div class="invoice-body">
      <div class="item">
        <h6><%= Product.find(@license.product_id).title %></h6>
        <p>License term: one year</p>
      </div>
      <div class="amount">
        <p><%= number_to_currency(@license.price) %></p>
      </div>
    </div>
    <div class="invoice-total">
      <div class="tax">
        <h6>Tax:</h6>
        <p>$0.00</p>
      </div>
      <div class="total">
        <h6>Total Due:</h6>
        <span><%= number_to_currency(@license.price) %></span>
      </div>
    </div>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="License Fee"
    data-amount=@license.price
    data-locale="auto">
    </script>

  </div>
</section>

<script>
  const paymentBtn = $('.stripe-button-el');
  paymentBtn[0].firstChild.innerText = "Pay Now"
  paymentBtn.addClass('waves-effect')
</script>